version: "3"

services:
  app:
    build: ./
    ports:
      - 8090:80
    volumes:
      - ./app:/app
    environment:
      - FLASK_APP=app/main.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=80'
    restart: unless-stopped
